import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DirectionProvider } from "@/components/ui/direction";
import { Toaster } from "sonner";
import Header from "@/components/Header";

import NextTopLoader from "nextjs-toploader";

const cairo = Cairo({ subsets: ["arabic"], variable: "--font-cairo" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={cn("h-full", "antialiased", cairo.className)}
    >
      <body className="min-h-full flex flex-col">
        <NextTopLoader color="black" />

        <Toaster position="top-center" />
        <DirectionProvider dir="rtl">
          <Header />
          {children}
        </DirectionProvider>
      </body>
    </html>
  );
}
